# Site settings
title: Aditya Pratap Singh
header-img: img/dist/home-bg.jpg
description: "Personal blog"
email: aditya.singh90@hotmail.com
baseurl: ""
url: "http://www.adityapsingh.com"
twitter_username: aditya_psingh
github_username:  addi90
facebook_username:  ''
linkedin_url: 'https://in.linkedin.com/pub/aditya-pratap-singh/50/7b8/929'

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
